# Generated by Django 3.0.5 on 2020-04-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to='books/'),
        ),
    ]
